version: '3.7'

services:

  keycloak:
     image: quay.io/keycloak/keycloak:latest
     container_name: keycloak
     restart: always
     ports:
      - "80:8080" # Listen to HTTP on host port 80 and forward to keycloak on 8080
      - "443:8443" # Listen to HTTPS on host port 443 and forward to keycloak on 443
     
     volumes:
       - "./tmp/safenet/SafenetOtpRealm.json:/tmp/safenet/SafenetOtpRealm.json" # Mount the SafeNet agent config 
       - "./tmp/safenet/sas-login-ui/:/opt/jboss/keycloak/themes/sas-login-ui/" # Mount the SAS/STA theme
       
     environment:
       - "KEYCLOAK_IMPORT:/tmp/SafenetOtpRealm.json" # This is the SafeNet KeyCloak agent configuration from mounted volume
       - JAVA_OPTS_APPEND="-D keycloak.profile.feature.upload_script=enabled"
       - KEYCLOAK_USER=admin
       - "KEYCLOAK_PASSWORD=password" # Change the password buddy!
       - AUTH_PROFILE=basicAuth
       - "KEYCLOAK_HOSTNAME=fqdn" # Set the hostname / FQDN
       - "KEYCLOAK_DEFAULT_THEME=sas-login-ui" # Here we make the SAS/STA theme default
